# Don't print a new line at the start of the prompt
add_newline = false
scan_timeout = 10

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'
vicmd_symbol = '[\$](bold green)'

[username]
style_root = "bold red"
style_user = "bold green"
show_always = true

[status]
disabled = false
style = "fg:red dimmed"
symbol = "✖"
format = "[\\[$symbol \\($status\\)\\]]($style) "

[package]
disabled = true

[java]
disabled = true

[nodejs]
disabled = true

[golang]
disabled = true

[dotnet]
disabled = true

[conda]
disabled = true

[nix_shell]
disabled = true

[memory_usage]
disabled = true

[battery]
disabled = true

[aws]
disabled = true

[ruby]
disabled = true

[php]
disabled = true

[crystal]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[kubernetes]
disabled = true

[line_break]
disabled = false

[time]
disabled = true

[cmd_duration]
style = "bold green"

[git_branch]
disabled = false

[git_state]
disabled = false

[git_status]
disabled = false

[git_commit]
disabled = false
commit_hash_length = 7

[hg_branch]
disabled = true

[singularity]
disabled = true

[terraform]
disabled = true

[helm]
disabled = true

[gcloud]
disabled = true

[swift]
disabled = true

[shlvl]
disabled = true
