repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-added-large-files
  - id: check-shebang-scripts-are-executable
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: mixed-line-ending
    args: [ --fix=no ]
- repo: local
  hooks:
    - id: gitleaks
      name: gitleaks
      description: Detect hardcoded secrets using Gitleaks
      language: system
      entry: gitleaks
      args: ["protect", "--verbose", "--redact", "--staged"]
    - id: stylua
      name: stylua
      description: Format lua files
      language: system
      entry: stylua
      types: [lua]
      args: ["--check"]
    - id: shfmt
      name: shfmt
      description: Format shell files
      minimum_pre_commit_version: 2.4.0
      language: system
      types: [shell]
      entry: shfmt
      args: ["--case-indent", "--binary-next-line", "--simplify"]