# Don't print a new line at the start of the prompt
add_newline = false
scan_timeout = 30

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
symbol = "➜"     # The "symbol" segment is being set to "➜"

[username]
style_root = "bold red"
style_user = "bold green"
show_always = true

[package]
disabled = true

[java]
disabled = true

[dotnet]
disabled = true

[conda]
disabled = true

[nix_shell]
disabled = true

[memory_usage]
disabled = true

[battery]
disabled = true

[aws]
disabled = true

[ruby]
disabled = true

[time]
disabled = true

[cmd_duration]
style = "bold green"