#!/bin/dash

read -r type target
if [ -z "${type}" ] || [ -z "${target}" ]; then
	exit 1
fi

case "${type}" in
	URL ) xdg-open "${target}" ;;
	VIDEO ) mpv --ytdl-format='bestvideo[fps<=60][height<=1080][vcodec=avc1]/mp4' "${target}";;
	AUDIO ) mpv --profile=low-latency --no-video --cache=auto --demuxer-max-back-bytes=2097152 --demuxer-max-bytes=2097152 --ytdl-format='bestaudio[ext=webm]/bestaudio[ext=m4a]/bestaudio' "${target}";;
	* ) printf '%s\n' 'Unsupported format.'; exit 2 ;;
esac

# vi:set ft=sh ts=4 sw=4 noet:
